version: 2
updates:
  - package-ecosystem: 'npm' # pnpm, yarn, npm 모두 "npm"을 사용하며, pnpm-lock.yaml을 자동으로 감지합니다.
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'daily'
